apiVersion: aggregation.grafana.app/v0alpha1
kind: DataPlaneService
metadata:
  name: v0alpha1.prometheus.grafana.app
spec:
  group: prometheus.grafana.app
  version: v0alpha1
  services:
    - type: data
